name = "spark-connector"
title = "MongoDB Spark Connector"

intersphinx = ["https://www.mongodb.com/docs/manual/objects.inv"]

toc_landing_pages = ["/java-api", "/python-api", "/scala-api", "/r-api"]

[constants]
current-version = "3.0.2"
spark-core-version = "3.0.2"
spark-sql-version = "3.0.2"
scala-version = "2.12"
scala-version-full = "2.12.13"

[substitutions]
copy = "unicode:: U+000A9"
ent-build = "MongoDB Enterprise"

[[banners]]
targets = ["*"]
variant = "info"
value = """\
    This version of the documentation is archived and no longer \
    supported. See the `current documentation <https://www.mongodb.com/docs/spark-connector/current/>`__ for \
    the latest version of the MongoDB Connector for Spark.
    """

