name = "spark-connector"
title = "MongoDB Spark Connector"

intersphinx = ["https://www.mongodb.com/docs/manual/objects.inv"]

toc_landing_pages = ["/java-api", "/python-api", "/scala-api", "/r-api"]

[constants]
current-version = "2.4.3"
spark-core-version = "2.4.3"
spark-sql-version = "2.4.3"

[substitutions]
copy = "unicode:: U+000A9"
ent-build = "MongoDB Enterprise"
